packages:
  - packages/types
  - packages/browser
  - packages/worker
  - packages/react
  - packages/server
  - packages/test
  - packages/storybook
  - examples/*
  - website

catalog:
  wrangler: 4.110.0
