/**
 * Test worker: Counter + Aggregator DOs for fromActorKit integration tests.
 *
 * Counter: simple incrementable counter
 * Aggregator: invokes Counter via fromActorKit, mirrors counter state
 */
import type {
  ActorKitSystemEvent,
  AnyActorServer,
  BaseActorKitEvent,
  CallerSnapshotFrom,
  WithActorKitEvent,
  WithActorKitInput,
} from "@actor-kit/types";
import {
  createActorKitRouter,
  createMachineServer,
  fromActorKit,
} from "@actor-kit/worker";
// DurableObject import available via cloudflare:workers in the Workers runtime
import { assign, sendTo, setup } from "xstate";
import { z } from "zod";

// ============================================================================
// Env — uses the Cloudflare.Env generated by `wrangler types`, extended
// with the actor-kit index signature required by ActorKitEnv.
// ============================================================================

export interface Env extends Cloudflare.Env {
  [key: string]: DurableObjectNamespace<AnyActorServer> | unknown;
}

// ============================================================================
// Counter DO
// ============================================================================

const CounterClientEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("INCREMENT") }),
]);

const CounterServiceEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("INCREMENT") }),
]);

const CounterInputPropsSchema = z.object({});

type CounterClientEvent = z.infer<typeof CounterClientEventSchema>;
type CounterServiceEvent = z.infer<typeof CounterServiceEventSchema>;

type CounterEvent = (
  | WithActorKitEvent<CounterClientEvent, "client">
  | WithActorKitEvent<CounterServiceEvent, "service">
  | ActorKitSystemEvent
) &
  BaseActorKitEvent<Env>;

type CounterInput = WithActorKitInput<
  z.infer<typeof CounterInputPropsSchema>,
  Env
>;

type CounterServerContext = {
  public: { count: number };
  private: Record<string, never>;
};

const counterMachine = setup({
  types: {
    context: {} as CounterServerContext,
    events: {} as CounterEvent,
    input: {} as CounterInput,
  },
  actions: {
    increment: assign({
      public: ({ context }) => ({ count: context.public.count + 1 }),
    }),
  },
}).createMachine({
  id: "counter",
  initial: "active",
  context: () => ({ public: { count: 0 }, private: {} }),
  states: {
    active: {
      on: { INCREMENT: { actions: "increment" } },
    },
  },
});

export type CounterMachine = typeof counterMachine;

export const Counter = createMachineServer({
  machine: counterMachine,
  schemas: {
    clientEvent: CounterClientEventSchema,
    serviceEvent: CounterServiceEventSchema,
    inputProps: CounterInputPropsSchema,
  },
  options: { persisted: true },
});

// ============================================================================
// Aggregator DO — uses fromActorKit to connect to Counter
// ============================================================================

const AggregatorClientEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("INCREMENT_COUNTER") }),
]);

const AggregatorServiceEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("NOOP") }),
]);

const AggregatorInputPropsSchema = z.object({});

type AggregatorClientEvent = z.infer<typeof AggregatorClientEventSchema>;

type CounterUpdatedEvent = {
  type: "COUNTER_UPDATED";
  actorType: "counter";
  actorId: string;
  snapshot: CallerSnapshotFrom<CounterMachine>;
  operations: unknown[];
};

type AggregatorEvent = (
  | WithActorKitEvent<AggregatorClientEvent, "client">
  | WithActorKitEvent<z.infer<typeof AggregatorServiceEventSchema>, "service">
  | ActorKitSystemEvent
  | CounterUpdatedEvent
) &
  BaseActorKitEvent<Env>;

type AggregatorInput = WithActorKitInput<
  z.infer<typeof AggregatorInputPropsSchema>,
  Env
>;

type AggregatorServerContext = {
  public: { counterCount: number; counterId: string };
  private: Record<string, never>;
};

const aggregatorMachine = setup({
  types: {
    context: {} as AggregatorServerContext,
    events: {} as AggregatorEvent,
    input: {} as AggregatorInput,
  },
  actors: {
    counterConnection: fromActorKit<CounterMachine>("counter"),
  },
  guards: {
    isCounterUpdated: ({ event }) => event.type === "COUNTER_UPDATED",
  },
  actions: {
    updateCounterSnapshot: assign({
      public: ({ context, event }) => {
        // Guard ensures this is a CounterUpdatedEvent
        const { snapshot } = event as CounterUpdatedEvent;
        return { ...context.public, counterCount: snapshot.public.count };
      },
    }),
    forwardIncrement: sendTo("counterConnection", { type: "INCREMENT" }),
  },
}).createMachine({
  id: "aggregator",
  initial: "active",
  context: ({ input }) => ({
    public: { counterCount: 0, counterId: `counter-for-${input.id}` },
    private: {},
  }),
  states: {
    active: {
      invoke: {
        id: "counterConnection",
        src: "counterConnection",
        // XState's invoke input function receives the init event which carries
        // the machine input, but XState doesn't type it — this cast is required.
        input: ({ context, event }) => {
          const initEvent = event as { input: AggregatorInput };
          return {
            server: initEvent.input.env.COUNTER,
            actorId: context.public.counterId,
            actorInput: {},
            caller: { id: "aggregator", type: "service" as const },
            signingKey: initEvent.input.env.ACTOR_KIT_SECRET,
            eventSchema: CounterServiceEventSchema,
          };
        },
      },
      on: {
        COUNTER_UPDATED: { actions: "updateCounterSnapshot" },
        INCREMENT_COUNTER: { actions: "forwardIncrement" },
      },
    },
  },
});

export type AggregatorMachine = typeof aggregatorMachine;

export const Aggregator = createMachineServer({
  machine: aggregatorMachine,
  schemas: {
    clientEvent: AggregatorClientEventSchema,
    serviceEvent: AggregatorServiceEventSchema,
    inputProps: AggregatorInputPropsSchema,
  },
  options: { persisted: true },
});

// ============================================================================
// Timer DO — exercises the SQLite storage layer: event log, SQLite snapshots,
// and a hibernation-safe `after` delay driven by the alarm scheduler.
// ============================================================================

const TimerClientEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("INCREMENT") }),
  z.object({ type: z.literal("START_TIMER") }),
]);

const TimerServiceEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("NOOP") }),
]);

const TimerInputPropsSchema = z.object({});

type TimerClientEvent = z.infer<typeof TimerClientEventSchema>;
type TimerServiceEvent = z.infer<typeof TimerServiceEventSchema>;

type TimerEvent = (
  | WithActorKitEvent<TimerClientEvent, "client">
  | WithActorKitEvent<TimerServiceEvent, "service">
  | ActorKitSystemEvent
) &
  BaseActorKitEvent<Env>;

type TimerInput = WithActorKitInput<z.infer<typeof TimerInputPropsSchema>, Env>;

type TimerServerContext = {
  public: { count: number; rang: boolean };
  private: Record<string, never>;
};

// The delay is short so the test only waits a beat; what matters is that it's
// scheduled as a *persisted DO alarm* (SQLite), not an in-memory setTimeout.
const TIMER_DELAY_MS = 50;

const timerMachine = setup({
  types: {
    context: {} as TimerServerContext,
    events: {} as TimerEvent,
    input: {} as TimerInput,
  },
  delays: { tick: TIMER_DELAY_MS },
  actions: {
    increment: assign({
      public: ({ context }) => ({ ...context.public, count: context.public.count + 1 }),
    }),
    ring: assign({
      public: ({ context }) => ({ ...context.public, rang: true }),
    }),
  },
}).createMachine({
  id: "timer",
  initial: "idle",
  context: () => ({ public: { count: 0, rang: false }, private: {} }),
  states: {
    idle: {
      on: {
        INCREMENT: { actions: "increment" },
        START_TIMER: "ticking",
      },
    },
    ticking: {
      after: { tick: { target: "rang", actions: "ring" } },
    },
    rang: { type: "final" },
  },
});

export type TimerMachine = typeof timerMachine;

const TimerServer = createMachineServer({
  machine: timerMachine,
  schemas: {
    clientEvent: TimerClientEventSchema,
    serviceEvent: TimerServiceEventSchema,
    inputProps: TimerInputPropsSchema,
  },
  options: { persisted: true, sqlite: { eventLog: true }, enableAlarms: true },
});

/** Internals exposed by the SQLite layer, for test inspection only. */
interface TimerInternals {
  sqliteStorage: {
    getEvents(): unknown[];
    getLatestSnapshot(): unknown;
  } | null;
  alarmManager: {
    getPendingAlarms(): { type: string }[];
  } | null;
}

/**
 * Subclass adds RPC inspection methods. The SQLite fields are public on the
 * machine-server impl but erased to `ActorServer` in the public type, so we
 * reach them through a narrow internal cast (test-only).
 */
export class Timer extends TimerServer {
  /** Number of client/service events recorded to the SQLite event log. */
  getEventCount(): number {
    const s = (this as unknown as TimerInternals).sqliteStorage;
    return s ? s.getEvents().length : 0;
  }
  /** Whether a snapshot row has been persisted to SQLite. */
  hasPersistedSnapshot(): boolean {
    const s = (this as unknown as TimerInternals).sqliteStorage;
    return s ? s.getLatestSnapshot() != null : false;
  }
  /** Count of pending `xstate-delay` alarms persisted in SQLite. */
  pendingXStateAlarms(): number {
    const a = (this as unknown as TimerInternals).alarmManager;
    return a ? a.getPendingAlarms().filter((x) => x.type === "xstate-delay").length : 0;
  }
}

// ============================================================================
// Worker entrypoint
// ============================================================================

const router = createActorKitRouter<Env>(["counter", "aggregator"]);

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/health") return new Response("ok");
    if (url.pathname.startsWith("/api/")) return router(request, env);
    return new Response("test worker", { status: 200 });
  },
};
